In [1]:
import numpy as np

# Definimos dos matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 3]])

# Suma de matrices
suma = A + B

# Multiplicación de matrices
multiplicacion = np.dot(A, B)

# Determinante de A
det_A = np.linalg.det(A)

# Inversa de A
inv_A = np.linalg.inv(A)

# Autovalores y autovectores de A
autovalores, autovectores = np.linalg.eig(A)

print("Suma:\n", suma)
print("Multiplicación:\n", multiplicacion)
print("Determinante de A:", det_A)
print("Inversa de A:\n", inv_A)
print("Autovalores de A:", autovalores)
print("Autovectores de A:\n", autovectores)

Suma:
 [[3 2]
 [4 7]]
Multiplicación:
 [[ 4  6]
 [10 12]]
Determinante de A: -2.0000000000000004
Inversa de A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Autovalores de A: [-0.37228132  5.37228132]
Autovectores de A:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [2]:
from sklearn.decomposition import PCA
import numpy as np

# Creamos datos de ejemplo (imágenes representadas como matrices)
imagenes = np.random.rand(100, 1000)  # 100 imágenes, cada una con 1000 píxeles

# Aplicamos PCA para reducir a 50 dimensiones
pca = PCA(n_components=50)
imagenes_reducidas = pca.fit_transform(imagenes)

print("Dimensión original:", imagenes.shape)
print("Nueva dimensión:", imagenes_reducidas.shape)

Dimensión original: (100, 1000)
Nueva dimensión: (100, 50)


In [3]:
from sklearn.linear_model import LinearRegression

# Datos de ejemplo: [metros_cuadrados, habitaciones]
X = np.array([[50, 2], [80, 3], [120, 4], [150, 5]])  
y = np.array([100000, 200000, 300000, 400000])  # Precio de las casas

# Creamos el modelo y entrenamos
modelo = LinearRegression()
modelo.fit(X, y)

# Predicción para una nueva casa (100m², 3 habitaciones)
prediccion = modelo.predict([[100, 3]])

print("Precio estimado:", prediccion[0])

Precio estimado: 199999.99999999994
