In [2]:
import numpy as np

In [ ]:
arr = np.arange(start=1,spot=100, num=100)

In [3]:
arr = np.ones(10)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [4]:
arr = np.full(shape=(4,2), fill_value=8)
print(arr)

[[8 8]
 [8 8]
 [8 8]
 [8 8]]


In [5]:
print(np.random.rand(4,2))

[[0.01221379 0.33190729]
 [0.61899621 0.82662084]
 [0.53331568 0.01803103]
 [0.14985155 0.39212981]]


In [7]:
print(np.random.uniform(low=4,high=2, size=(2,2)))

[[2.21312318 2.85281785]
 [2.75703348 2.00879985]]


In [11]:
print(np.random.randn(4,2))

[[ 1.96958461 -0.39488003]
 [ 1.01874978 -0.0201348 ]
 [-2.17276453 -1.25668903]
 [ 0.64145257 -0.55481259]]


In [12]:
matriz = np.arange(16).reshape(4,4)
print(matriz)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [13]:
print(matriz[0,1])

1


In [14]:
print(matriz[0])

[0 1 2 3]


In [15]:
print(matriz[:,1])

[ 1  5  9 13]


In [18]:
a= np.arange(0,6)

In [20]:
print(a+10)

[10 11 12 13 14 15]
